// SPDX-License-Identifier: Apache-2.0
using Hedera.Hashgraph.SDK.Cryptography;
using System.IO;

namespace Hedera.Hashgraph.Tests.SDK.Keys
{
    /// <include file="tets-keys-keystore.cs.xml" path='docs/member[@name="T:Hedera.Hashgraph.Tests.SDK.Keys.KeystoreTest"]' />
    public class KeystoreTest
    {
        private static readonly string TEST_KEY_STR = "302e020100300506032b657004220420db484b828e64b2d8f12ce3c0a0e93a0b8cce7af1bb8f39c97732394482538e10";
        private static readonly string PASSPHRASE = "asdf1234";
        [Fact]
        /// <include file="tets-keys-keystore.cs.xml" path='docs/member[@name="M:Hedera.Hashgraph.Tests.SDK.Keys.KeystoreTest.KeystoreFromStream"]' />
        public virtual void KeystoreFromStream()
        {
            // keystore file generated by hedera-sdk-js from `testKeyStr` and `passphrase`
            // NOT USED ANYWHERE
            Keystore keystore = Keystore.FromStream(Resources.TestKeystore_Stream, PASSPHRASE);
            PrivateKey privateKey = keystore.GetEd25519();

            Assert.Equal(privateKey.ToString(), TEST_KEY_STR);
        }
        [Fact]
        /// <include file="tets-keys-keystore.cs.xml" path='docs/member[@name="M:Hedera.Hashgraph.Tests.SDK.Keys.KeystoreTest.KeystoreFromStreamV2"]' />
        public virtual void KeystoreFromStreamV2()
        {
            // keystore file generated by hedera-sdk-js from `testKeyStr` and `passphrase`
            // NOT USED ANYWHERE
            Keystore keystore = Keystore.FromStream(Resources.TestKeystore2_Stream, PASSPHRASE);
            PrivateKey privateKey = keystore.GetEd25519();

            Assert.Equal(privateKey.ToString(), TEST_KEY_STR);
        }
        [Fact]
        /// <include file="tets-keys-keystore.cs.xml" path='docs/member[@name="M:Hedera.Hashgraph.Tests.SDK.Keys.KeystoreTest.KeystoreToStream"]' />
        public virtual void KeystoreToStream()
        {
            PrivateKey privateKey = PrivateKey.FromString(TEST_KEY_STR);
            Keystore keystore = new Keystore(privateKey);
			MemoryStream outputStream = new ();
            keystore.Export(outputStream, PASSPHRASE);
            Keystore keystore2 = Keystore.FromStream(outputStream, PASSPHRASE);
            PrivateKey privateKey2 = keystore2.GetEd25519();

            Assert.Equal(privateKey2.ToString(), TEST_KEY_STR);
        }
    }
}
