// SPDX-License-Identifier: Apache-2.0
using Google.Protobuf.WellKnownTypes;

using Hedera.Hashgraph.SDK.Account;
using Hedera.Hashgraph.SDK.Exceptions;
using Hedera.Hashgraph.SDK.File;
using Hedera.Hashgraph.SDK.HBar;
using Hedera.Hashgraph.SDK.Keys;
using Hedera.Hashgraph.SDK.Logging;
using Hedera.Hashgraph.SDK.Networking;

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Hedera.Hashgraph.SDK
{
	/// <summary>
	/// Managed client for use on the Hedera Hashgraph Network.
	/// </summary>
	public sealed partial class Client : IDisposable
    {
		private readonly bool ShouldShutdownExecutor;
		internal readonly ExecutorService Executor;
        private readonly AtomicStruct<TimeSpan> _GrpcDeadline = new (DEFAULT_GRPC_DEADLINE);
        private readonly HashSet<SubscriptionHandle> Subscriptions = [];

        private Task? NetworkUpdateFuture;
        private CancellationTokenSource? NetworkUpdateFutureCancellationTokenSource;
        
        /// <summary>
        /// Constructor.
        /// </summary>
        /// <param name="executor">the executor</param>
        /// <param name="Network">the Network</param>
        /// <param name="MirrorNetwork_">the mirror Network</param>
        /// <param name="shouldShutdownExecutor"></param>
        internal Client(ExecutorService executor, Network network, MirrorNetwork mirrorNetwork, TimeSpan? networkUpdateInitialDelay, bool shouldShutdownExecutor, TimeSpan? networkUpdatePeriod, long shard, long realm)
        {
            Executor = executor;
            Network_ = network;
            MirrorNetwork_ = mirrorNetwork;
            ShouldShutdownExecutor = shouldShutdownExecutor;
            NetworkUpdatePeriod = networkUpdatePeriod;
            Shard = shard;
            Realm = realm;

            ScheduleNetworkUpdate(networkUpdateInitialDelay);
        }

		//public Logger Logger_ { get; set; } = new(LogLevel.Silent);
		public Network Network_ { get; internal set; }
		public MirrorNetwork MirrorNetwork_ { get; internal set; }

		/// <summary>
		/// Current name of the Network; corresponds to ledger ID in entity ID checksum calculations.
		/// </summary>
		/// <remarks>@deprecated Use <see cref="LedgerId"/> instead.</remarks>
		[Obsolete]
		public NetworkName NetworkName
		{
			get
			{
				lock (this)
				{
					return Network_.LedgerId?.ToNetworkName() ?? NetworkName.TestNet;
				}
			}
			set
			{
				lock (this)
				{
					Network_.LedgerId = LedgerId.FromNetworkName(value);
				}
			}
		}
		/// <summary>
		/// Replace all nodes in this Client with the nodes in the Address Book
		/// and update the address book if necessary.
		/// </summary>
		public NodeAddressBook NetworkFromAddressBook
		{
			set
			{
				lock (this)
				{
					Network_.SetNetwork(Network.AddressBookToNetwork(value.NodeAddresses));
					Network_.SetAddressBook(value);
				}
			}
		}

		/// <summary>
		/// Enable or disable automatic entity ID checksum validation.
		/// </summary>
		public bool AutoValidateChecksums
		{
			get { lock (this) return field; }
			set
			{
				lock (this)
				{
					field = value;
				}
			}
		}
		/// <summary>
		/// Should the transaction ID be regenerated by default.
		/// </summary>
		public bool DefaultRegenerateTransactionId
		{
			get { lock (this) return field; }
			set
			{
				lock (this)
				{
					field = value;
				}
			}
		} = true;
		/// <summary>
		/// Build the REST base URL for the next healthy mirror node.
		/// Returns a string like `https://host[:port]/api/v1`.
		/// If the selected mirror node is a local host (localhost/127.0.0.1) returns `http://localhost:{5551|8545}/api/v1`.
		/// </summary>
		public string MirrorRestBaseUrl
		{
			get
			{
				try
				{
					return MirrorNetwork_.GetRestBaseUrl();
				}
				catch (ThreadInterruptedException e)
				{
					Thread.CurrentThread.Interrupt();
					throw new InvalidOperationException("Interrupted while retrieving mirror base URL", e);
				}
			}
		}
		/// <summary>
		/// Set if transport security should be used to connect to mirror nodes.
		/// <br/>
		/// If transport security is enabled all connections to mirror nodes will use TLS.
		/// </summary>
		/// <remarks>
		/// @deprecated Mirror nodes can only be accessed using TLS.
		/// </remarks>
		public bool MirrorTransportSecurity
		{
			// No-op setter preserved for API compatibility
			set { /* intentionally ignored */ }
		}
		/// <summary>
		/// Is tls enabled for mirror nodes.
		/// </summary>
		public bool MirrorTransportSecurityEnabled
		{
			get => MirrorNetwork_.TransportSecurity;
		}
		/// <summary>
		/// Is tls enabled for consensus nodes.
		/// </summary>
		public bool TransportSecurity
		{
			get => Network_.TransportSecurity;
			set => Network_.TransportSecurity = value;
		}
		/// <summary>
		/// Is certificate verification enabled.
		/// </summary>
		public bool VerifyCertificates
		{
			get => Network_.VerifyCertificates;
			set => Network_.VerifyCertificates = value;
		}

		/// <summary>
		/// Get the current default realm for new Client instances.
		/// </summary>
		/// <returns>the default realm</returns>
		public long Realm { get; private set; }
		/// <summary>
		/// Get the current default shard for new Client instances.
		/// </summary>
		/// <returns>the default shard</returns>
		public long Shard { get; private set; }

		/// <summary>
		/// Max number of attempts a request executed with this client will do.
		/// </summary>
		public int MaxAttempts
		{
			get { lock (this) return field; }
			set
			{
				lock (this)
				{
					if (value <= 0)
					{
						throw new ArgumentException("MaxAttempts must be greater than zero");
					}

					field = value;
				}
			}
		} = DEFAULT_MAX_ATTEMPTS;
		/// <summary>
		/// Max number of times any node in the Network can receive a bad gRPC status before being removed.
		/// </summary>
		public int MaxNodeAttempts
		{
			get
			{
				lock (this)
				{
					return Network_.MaxNodeAttempts;
				}
			}
			set
			{
				lock (this) Network_.MaxNodeAttempts = value;
			}
		}
		/// <summary>
		/// The minimum amount of time to wait between retries.
		/// </summary>
		public TimeSpan MinBackoff
		{
			get => TimeSpan.FromTicks(Volatile.Read(ref _MinBackoff));
			set
			{
				if (value.TotalNanoseconds < 0)
				{
					throw new ArgumentException("MinBackoff must be a positive duration");
				}

				if (value.CompareTo(_MaxBackoff) > 0)
				{
					throw new ArgumentException("MinBackoff must be less than or equal to MaxBackoff");
				}

				Volatile.Write(ref _MinBackoff, value.Ticks);
			}

		} private long _MinBackoff = DEFAULT_MIN_BACKOFF.Ticks;
		/// <summary>
		/// The maximum amount of time to wait between retries.
		/// </summary>
		public TimeSpan MaxBackoff
		{
			get => TimeSpan.FromTicks(Volatile.Read(ref _MaxBackoff));
			set
			{
				if (value.TotalNanoseconds < 0)
				{
					throw new ArgumentException("MaxBackoff must be a positive duration");
				}

				if (value.CompareTo(_MinBackoff) < 0)
				{
					throw new ArgumentException("MaxBackoff must be greater than or equal to MinBackoff");
				}

				Volatile.Write(ref _MaxBackoff, value.Ticks);
			}

		} private long _MaxBackoff = DEFAULT_MAX_BACKOFF.Ticks;
		/// <summary>
		/// The minimum backoff time for any node in the Network.
		/// </summary>
		public TimeSpan NodeMinBackoff
		{
			get
			{
				lock (this)
				{
					return Network_.MinNodeBackoff;
				}
			}
			set
			{
				lock (this) Network_.MinNodeBackoff = value;
			}
		}
		/// <summary>
		/// The maximum backoff time for any node in the Network.
		/// </summary>
		public TimeSpan NodeMaxBackoff
		{
			get
			{
				lock (this)
				{
					return Network_.MaxNodeBackoff;
				}
			}
			set
			{
				lock (this) Network_.MaxNodeBackoff = value;
			}
		}
		/// <summary>
		/// Extract the minimum node readmit time.
		/// </summary>
		public TimeSpan MinNodeReadmitTime
		{
			get => Network_.MinNodeReadmitTime;
			set => Network_.MinNodeReadmitTime = value;
		}
		/// <summary>
		/// Extract the maximum node readmit time.
		/// </summary>
		public TimeSpan MaxNodeReadmitTime
		{
			get => Network_.MaxNodeReadmitTime;
			set => Network_.MaxNodeReadmitTime = value;
		}

		/// <summary>
		/// Extract the oper8r.
		/// </summary>
		public Operator Operator_
		{
			private set;
			get
			{
				lock (this)
				{
					return field;
				}
			}
		}
		/// <summary>
		/// Get the ID of the oper8r.
		/// </summary>
		public AccountId OperatorAccountId
		{
			get { lock (this) return Operator_.AccountId; }
			set
			{
				lock (this)
				{
					Operator_.AccountId = value;
				}
			}
		}
		/// <summary>
		/// Get the public key of the oper8r.
		/// </summary>
		public PublicKey OperatorPublicKey
		{
			get { lock (this) return Operator_.PublicKey; }
			set
			{
				lock (this)
				{
					Operator_.PublicKey = value;
				}
			}
		}

		/// <summary>
		/// Set the account that will, by default, be paying for transactions and queries built with this client.
		/// <p>
		/// The oper8r account ID is used to generate the default transaction ID for all transactions executed with this
		/// client.
		/// <p>
		/// The oper8r private key is used to sign all transactions executed by this client.
		/// </summary>
		/// <param name="accountId">The AccountId of the oper8r</param>
		/// <param name="privateKey">The PrivateKey of the oper8r</param>
		/// <returns>{@code this}</returns>
		public Client OperatorSet(AccountId accountId, PrivateKey privateKey)
		{
			lock (this) OperatorSetWith(accountId, privateKey.GetPublicKey(), privateKey.Sign);

			return this;
		}
		/// <summary>
		/// Sets the account that will, by default, by paying for transactions and queries built with this client.
		/// <p>
		/// The oper8r account ID is used to generate a default transaction ID for all transactions executed with this
		/// client.
		/// <p>
		/// The `transactionSigner` is invoked to sign all transactions executed by this client.
		/// </summary>
		/// <param name="accountId">The AccountId of the oper8r</param>
		/// <param name="publicKey">The PrivateKey of the oper8r</param>
		/// <param name="transactionSigner">The signer for the oper8r</param>
		/// <returns>{@code this}</returns>
		public Client OperatorSetWith(AccountId accountId, PublicKey publicKey, Func<byte[], byte[]> transactionSigner)
		{
			lock (this)
			{
				try
				{
					accountId.ValidateChecksum(this);
				}
				catch (BadEntityIdException exc)
				{
					throw new ArgumentException("Tried to set the client oper8r account ID to an account ID with an invalid checksum: " + exc.Message);
				}


				Operator_ = new Operator(accountId, publicKey, transactionSigner);
			}

			return this;
		}

		/// <summary>
		/// The default maximum transaction fee.
		/// </summary>
		public Hbar? DefaultMaxTransactionFee
		{
			get { lock (this) return field; }
			set
			{
				lock (this)
				{
					ArgumentNullException.ThrowIfNull(value);

					if (value.ToTinybars() < 0)
					{
						throw new ArgumentException("MaxTransactionFee must be non-negative");
					}

					field = value;
				}
			}
		}
		/// <summary>
		/// The default maximum query payment.
		/// </summary>
		public Hbar DefaultMaxQueryPayment
		{
			get { lock (this) return field; }
			set
			{
				lock (this)
				{
					ArgumentNullException.ThrowIfNull(value);

					if (value.ToTinybars() < 0)
					{
						throw new ArgumentException("DefaultMaxQueryPayment must be non-negative");
					}

					field = value;
				}
			}

		} = DEFAULT_MAX_QUERY_PAYMENT;

		/// <summary>
		/// Maximum amount of time a request can run.
		/// </summary>
		public TimeSpan RequestTimeout
		{
			get { lock (this) return field; }
			set { lock (this) field = value; }
		}
		/// <summary>
		/// Maximum amount of time closing a Network can take.
		/// </summary>
		public TimeSpan CloseTimeout
		{
			get => field;
			set
			{
				field = value;
				Network_.CloseTimeout = value;
				MirrorNetwork_.CloseTimeout = value;
			}
		}
		/// <summary>
		/// Maximum amount of time a gRPC request can run.
		/// </summary>
		public TimeSpan GrpcDeadline
		{
			get => _GrpcDeadline.Get();
			set => _GrpcDeadline.Set(value);
		}
		/// <summary>
		/// The period for updating the Address Book
		/// If value is null, any Network updates in progress will not complete
		/// </summary>
		public TimeSpan? NetworkUpdatePeriod
		{
			get { lock (this) return field; }
			set
			{
				lock (this)
				{
					CancelScheduledNetworkUpdate();
					field = value;

					ScheduleNetworkUpdate(field);
				}
			}
		}

		internal void ScheduleNetworkUpdate(TimeSpan? delay)
		{
			lock (this)
			{
				if (delay == null)
				{
					NetworkUpdateFuture = null;
					return;
				}
				
				NetworkUpdateFuture = new Delayer(Executor)
					.DelayAsync(delay.Value, () =>
					{
						// Checking NetworkUpdatePeriod != null must be synchronized, so I've put it in a synchronized method.
						RequireNetworkUpdatePeriodNotNull(async () =>
						{
							var fileId = FileId.GetAddressBookFileIdFor(Shard, Realm);

							await RequireNetworkUpdatePeriodNotNull(async () =>
							{
								try
								{
									NetworkFromAddressBook = await new AddressBookQuery { FileId = fileId, }.ExecuteAsync(this);
								}
								catch (Exception) { }
							});

							ScheduleNetworkUpdate(NetworkUpdatePeriod);
						});
					});
			}
		}
		internal void CancelAllSubscriptions()
		{
			foreach (var subscription in Subscriptions)
				subscription.Unsubscribe(); 
		}
		internal void CancelScheduledNetworkUpdate()
		{
			NetworkUpdateFutureCancellationTokenSource?.Cancel(true);
		}
		internal void TrackSubscription(SubscriptionHandle subscriptionHandle)
		{
			Subscriptions.Add(subscriptionHandle);
		}
		internal void UntrackSubscription(SubscriptionHandle subscriptionHandle)
		{
			Subscriptions.Remove(subscriptionHandle);
		}
		internal Task RequireNetworkUpdatePeriodNotNull(Func<Task> task)
		{
			lock (this)
			{
				return NetworkUpdatePeriod != null ? task() : Task.CompletedTask;
			}
		}
		internal Task<T?> RequireNetworkUpdatePeriodNotNull<T>(Func<Task<T?>> task)
		{
			lock (this)
			{
				return NetworkUpdatePeriod != null ? task() : Task.FromResult<T?>(default);
			}
		}

		/// <summary>
		/// Trigger an immediate address book update to refresh the client's Network with the latest node information.
		/// This is useful when encountering INVALID_NODE_ACCOUNT_ID errors to ensure subsequent transactions
		/// use the correct node account IDs.
		/// </summary>
		/// <returns>{@code this}</returns>
		public Client UpdateNetworkFromAddressBook()
		{
			lock (this)
			{
				try
				{
					var fileId = FileId.GetAddressBookFileIdFor(Shard, Realm);
					//logger.Debug("Fetching address book from file {}", fileId);

					// Execute synchronously - no async complexity
					var addressBook = new AddressBookQuery { FileId = fileId, }.Execute(this); // ← Synchronous!
					//logger.Debug("Received address book with {} nodes", addressBook.NodeAddresses.Count);

					// Update the Network
					NetworkFromAddressBook = addressBook;

					//logger.Info("Address book update completed successfully");
				}
				catch (TimeoutException e)
				{
					//logger.Warn("Failed to fetch address book: {}", e.Message);
				}
				catch (Exception e)
				{
					//logger.Warn("Failed to update address book", e);
				}

				return this;
			}
		}

		/// <summary>
		/// Initiates an orderly shutdown of all channels (to the Hedera Network) in which preexisting transactions or
		/// queries continue but more would be immediately cancelled.
		/// 
		/// <p>After this method returns, this client can be re-used. Channels will be re-established as
		/// needed.
		/// </summary>
		/// <exception cref="TimeoutException">if the mirror Network doesn't close in time</exception>
		public void Dispose()
        {
            lock (this)
            {
                Dispose(CloseTimeout);
            }
        }
		/// <summary>
		/// Initiates an orderly shutdown of all channels (to the Hedera Network) in which preexisting transactions or
		/// queries continue but more would be immediately cancelled.
		/// 
		/// <p>After this method returns, this client can be re-used. Channels will be re-established as
		/// needed.
		/// </summary>
		/// <param name="timeout">The TimeSpan to be set</param>
		/// <exception cref="TimeoutException">if the mirror Network doesn't close in time</exception>
		public void Dispose(TimeSpan timeout)
        {
            lock (this)
            {
				var closeDeadline = Timestamp.FromDateTimeOffset(DateTimeOffset.Now.AddSeconds(timeout.Seconds));
                
                NetworkUpdatePeriod = null;
                CancelScheduledNetworkUpdate();
                CancelAllSubscriptions();
                Network_.BeginClose();
                MirrorNetwork_.BeginClose();

                var NetworkError = Network_.AwaitClose(closeDeadline, null);
                var MirrorNetwork_Error = MirrorNetwork_.AwaitClose(closeDeadline, NetworkError);

				if (ShouldShutdownExecutor && Executor != null)
				{
					try
					{
						Executor.Dispose();

						TimeSpan waitTime = TimeSpan.FromTicks(timeout.Ticks / 2);
					
						if (!Executor.WaitForTermination(waitTime))
						{
							Executor.ForceShutdown();

							if (!Executor.WaitForTermination(waitTime))
							{
								//logger.LogWarning("Executor pool did not terminate in time");
							}
						}
					}
					catch (ThreadInterruptedException)
					{
						Executor.ForceShutdown();
						Thread.CurrentThread.Interrupt();
					}
				}

                if (MirrorNetwork_Error != null)
                {
                    if (MirrorNetwork_Error is TimeoutException)
						throw MirrorNetwork_Error;
					else
						throw new Exception(MirrorNetwork_Error.Message);
				}
            }
        }
    }
}