// SPDX-License-Identifier: Apache-2.0
using Org.Assertj.Core.Api.Assertions;
using Java.Io;
using Org.Junit.Jupiter.Api;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Text;

namespace Hedera.Hashgraph.Tests.SDK.SDK.Keys
{
    class KeystoreTest
    {
        private static readonly string TEST_KEY_STR = "302e020100300506032b657004220420db484b828e64b2d8f12ce3c0a0e93a0b8cce7af1bb8f39c97732394482538e10";
        private static readonly string PASSPHRASE = "asdf1234";
        public virtual void KeystoreFromStream()
        {

            // keystore file generated by hedera-sdk-js from `testKeyStr` and `passphrase`
            // NOT USED ANYWHERE
            InputStream inputStream = typeof(KeystoreTest).GetResourceAsStream("/test-keystore.bin");
            Keystore keystore = Keystore.FromStream(inputStream, PASSPHRASE);
            PrivateKey privateKey = keystore.GetEd25519();
            Assert.Equal(privateKey.ToString(), TEST_KEY_STR);
        }

        public virtual void KeystoreFromStreamV2()
        {

            // keystore file generated by hedera-sdk-js from `testKeyStr` and `passphrase`
            // NOT USED ANYWHERE
            InputStream inputStream = typeof(KeystoreTest).GetResourceAsStream("/test-keystore2.bin");
            Keystore keystore = Keystore.FromStream(inputStream, PASSPHRASE);
            PrivateKey privateKey = keystore.GetEd25519();
            Assert.Equal(privateKey.ToString(), TEST_KEY_STR);
        }

        public virtual void KeystoreToStream()
        {
            PrivateKey privateKey = PrivateKey.FromString(TEST_KEY_STR);
            Keystore keystore = new Keystore(privateKey);
            ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
            keystore.Export(outputStream, PASSPHRASE);
            Keystore keystore2 = Keystore.FromStream(new ByteArrayInputStream(outputStream.ToByteArray()), PASSPHRASE);
            PrivateKey privateKey2 = keystore2.GetEd25519();
            Assert.Equal(privateKey2.ToString(), TEST_KEY_STR);
        }
    }
}