<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<ImplicitUsings>disable</ImplicitUsings>
		<LangVersion>14</LangVersion>
		<Nullable>enable</Nullable>
		<TargetFramework>net10.0</TargetFramework>
		<RestoreAdditionalProjectSources>$(MSBuildProjectDirectory)\..\sdk-package</RestoreAdditionalProjectSources>
	</PropertyGroup>
	
	<ItemGroup>
		<PackageReference Include="Hedera.Hashgraph" Version="*" />
		<PackageReference Include="Hedera.Hashgraph.Proto" Version="*" />
		<PackageReference Include="Hedera.Hashgraph.Reference" Version="*" />
		<PackageReference Include="Hedera.Hashgraph.SDK" Version="*" />
	</ItemGroup>

</Project>
