// SPDX-License-Identifier: Apache-2.0
using Org.Assertj.Core.Api.Assertions;
using Java.Io;
using Java.Nio.Charset;
using Java.Util.Stream;
using Org.Assertj.Core.Api;
using Org.Bouncycastle.Math.Ec.Rfc8032;
using Org.Bouncycastle.Util.Encoders;
using Org.Junit.Jupiter.Api;
using Org.Junit.Jupiter.Params;
using Org.Junit.Jupiter.Params.Provider;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Text;

namespace Com.Hedera.Hashgraph.Sdk
{
    class Ed25519PrivateKeyTest
    {
        private static readonly string TEST_KEY_STR = "302e020100300506032b657004220420db484b828e64b2d8f12ce3c0a0e93a0b8cce7af1bb8f39c97732394482538e10";
        private static readonly string TEST_KEY_STR_RAW = "db484b828e64b2d8f12ce3c0a0e93a0b8cce7af1bb8f39c97732394482538e10";
        private static readonly string TEST_KEY_PEM = "-----BEGIN PRIVATE KEY-----\n" + "MC4CAQAwBQYDK2VwBCIEINtIS4KOZLLY8SzjwKDpOguMznrxu485yXcyOUSCU44Q\n" + "-----END PRIVATE KEY-----\n";
        // generated by hedera-sdk-js, not used anywhere
        private static readonly string MNEMONIC_STRING = "inmate flip alley wear offer often piece magnet surge toddler submit right radio absent pear floor belt raven price stove replace reduce plate home";
        private static readonly string MNEMONIC_PRIVATE_KEY = "302e020100300506032b657004220420853f15aecd22706b105da1d709b4ac05b4906170c2b9c7495dff9af49e1391da";
        private static readonly string MNEMONIC_LEGACY_STRING = "jolly kidnap tom lawn drunk chick optic lust mutter mole bride galley dense member sage neural widow decide curb aboard margin manure";
        private static readonly string MNEMONIC_LEGACY_PRIVATE_KEY = "302e020100300506032b657004220420882a565ad8cb45643892b5366c1ee1c1ef4a730c5ce821a219ff49b6bf173ddf";
        // backup phrase generated by the iOS wallet, not used anywhere
        private static readonly string IOS_MNEMONIC_STRING = "tiny denial casual grass skull spare awkward indoor ethics dash enough flavor good daughter early hard rug staff capable swallow raise flavor empty angle";
        // private key for "default account", should be index 0
        private static readonly string IOS_DEFAULT_PRIVATE_KEY = "5f66a51931e8c99089472e0d70516b6272b94dd772b967f8221e1077f966dbda2b60cf7ee8cf10ecd5a076bffad9a7c7b97df370ad758c0f1dd4ef738e04ceb6";
        // backup phrase generated by the Android wallet, also not used anywhere
        private static readonly string ANDROID_MNEMONIC_STRING = "ramp april job flavor surround pyramid fish sea good know blame gate village viable include mixed term draft among monitor swear swing novel track";
        // private key for "default account", should be index 0
        private static readonly string ANDROID_DEFAULT_PRIVATE_KEY = "c284c25b3a1458b59423bc289e83703b125c8eefec4d5aa1b393c2beb9f2bae66188a344ba75c43918ab12fa2ea4a92960eca029a2320d8c6a1c3b94e06c9985";
        private static readonly string PEM_PASSPHRASE = "this is a passphrase";
        private static readonly string TEST_VECTOR_PEM_PASSPHRASE = "asdasd123";
        /*
       # enter passphrase "this is a passphrase"
       echo '302e020100300506032b657004220420db484b828e64b2d8f12ce3c0a0e93a0b8cce7af1bb8f39c97732394482538e10' \
       | xxd -r -p \
       | openssl pkey -inform der -aes-128-cbc
    */
        private static readonly string ENCRYPTED_PEM = "-----BEGIN ENCRYPTED PRIVATE KEY-----\n" + "MIGbMFcGCSqGSIb3DQEFDTBKMCkGCSqGSIb3DQEFDDAcBAi8WY7Gy2tThQICCAAw\n" + "DAYIKoZIhvcNAgkFADAdBglghkgBZQMEAQIEEOq46NPss58chbjUn20NoK0EQG1x\n" + "R88hIXcWDOECttPTNlMXWJt7Wufm1YwBibrxmCq1QykIyTYhy1TZMyxyPxlYW6aV\n" + "9hlo4YEh3uEaCmfJzWM=\n" + "-----END ENCRYPTED PRIVATE KEY-----\n";
        private static readonly string MESSAGE_STR = "This is a message about the world.";
        private static readonly byte[] MESSAGE_BYTES = MESSAGE_STR.GetBytes(StandardCharsets.UTF_8);
        private static readonly string SIG_STR = "73bea53f31ca9c42a422ecb7516ec08d0bbd1a6bfd630ccf10ec1872454814d29f4a8011129cd007eab544af01a75f508285b591e5bed24b68f927751e49e30e";
        private static Stream<string> PrivKeyStrings()
        {
            return Stream.Of(TEST_KEY_STR, TEST_KEY_STR_RAW + "e0c8ec2758a5879ffac226a13c0c516b799e72e35141a0dd828f94d37988a4b7", TEST_KEY_STR_RAW);
        }

        virtual void KeyGenerates()
        {
            PrivateKey key = PrivateKey.GenerateED25519();
            AssertThat(key).IsNotNull();
            AssertThat(key.ToBytes()).IsNotNull();

            // we generate the chain code at the same time
            AssertThat(key.IsDerivable()).IsTrue();
        }

        virtual void KeySerialization()
        {
            PrivateKey key1 = PrivateKey.GenerateED25519();
            byte[] key1Bytes = key1.ToBytes();
            PrivateKey key2 = PrivateKey.FromBytes(key1Bytes);
            byte[] key2Bytes = key2.ToBytes();
            AssertThat(key2Bytes).ContainsExactly(key1Bytes);
        }

        virtual void KeySerialization2()
        {
            PrivateKey key1 = PrivateKey.GenerateED25519();
            byte[] key1Bytes = key1.ToBytesRaw();
            PrivateKey key2 = PrivateKey.FromBytesED25519(key1Bytes);
            byte[] key2Bytes = key2.ToBytesRaw();
            PrivateKey key3 = PrivateKey.FromBytes(key1Bytes);
            byte[] key3Bytes = key3.ToBytesRaw();
            AssertThat(key2Bytes).ContainsExactly(key1Bytes);
            AssertThat(key3Bytes).ContainsExactly(key1Bytes);
        }

        virtual void KeySerialization3()
        {
            PrivateKey key1 = PrivateKey.GenerateED25519();
            byte[] key1Bytes = key1.ToBytesDER();
            PrivateKey key2 = PrivateKey.FromBytesDER(key1Bytes);
            byte[] key2Bytes = key2.ToBytesDER();
            PrivateKey key3 = PrivateKey.FromBytes(key1Bytes);
            byte[] key3Bytes = key3.ToBytesDER();
            AssertThat(key2Bytes).ContainsExactly(key1Bytes);
            AssertThat(key3Bytes).ContainsExactly(key1Bytes);
        }

        virtual void KeyStringification()
        {
            PrivateKey key1 = PrivateKey.GenerateED25519();
            string key1String = key1.ToString();
            PrivateKey key2 = PrivateKey.FromString(key1String);
            string key2String = key2.ToString();
            Assert.Equal(key2String, key1String);
        }

        virtual void KeyStringification2()
        {
            PrivateKey key1 = PrivateKey.GenerateED25519();
            string key1String = key1.ToStringRaw();
            PrivateKey key2 = PrivateKey.FromStringED25519(key1String);
            string key2String = key2.ToStringRaw();
            PrivateKey key3 = PrivateKey.FromString(key1String);
            string key3String = key3.ToStringRaw();
            Assert.Equal(key2String, key1String);
            Assert.Equal(key3String, key1String);
        }

        virtual void KeyStringification3()
        {
            PrivateKey key1 = PrivateKey.GenerateED25519();
            string key1String = key1.ToStringDER();
            PrivateKey key2 = PrivateKey.FromStringDER(key1String);
            string key2String = key2.ToStringDER();
            PrivateKey key3 = PrivateKey.FromString(key1String);
            string key3String = key3.ToStringDER();
            Assert.Equal(key2String, key1String);
            Assert.Equal(key3String, key1String);
        }

        virtual void ExternalKeyDeserialize(string keyStr)
        {
            PrivateKey key = PrivateKey.FromString(keyStr);
            AssertThat(key).IsNotNull();

            // the above are all the same key
            Assert.Equal(key.ToString(), TEST_KEY_STR);
            Assert.Equal(key.ToStringDER(), TEST_KEY_STR);
            Assert.Equal(key.ToStringRaw(), TEST_KEY_STR_RAW);
        }

        virtual void KeyToString()
        {
            PrivateKey key = PrivateKey.FromString(TEST_KEY_STR);
            AssertThat(key).IsNotNull();
            Assert.Equal(key.ToString(), TEST_KEY_STR);
        }

        virtual void KeyFromPem()
        {
            StringReader stringReader = new StringReader(TEST_KEY_PEM);
            PrivateKey privateKey = PrivateKey.ReadPem(stringReader);
            Assert.Equal(privateKey.ToString(), TEST_KEY_STR);
        }

        virtual void KeyFromMnemonic()
        {
            Mnemonic mnemonic = Mnemonic.FromString(MNEMONIC_STRING);
            PrivateKey key = PrivateKey.FromMnemonic(mnemonic);
            PrivateKey key2 = PrivateKey.FromString(MNEMONIC_PRIVATE_KEY);
            AssertThat(key2.ToBytes()).ContainsExactly(key.ToBytes());
        }

        virtual void ValidateGenerated12()
        {
            Mnemonic mnemonic = Mnemonic.Generate12();
            Mnemonic.FromString(mnemonic.ToString());
        }

        virtual void ValidateLegacyMnemonic()
        {
            Mnemonic mnemonic = Mnemonic.FromString(MNEMONIC_LEGACY_STRING);
            PrivateKey key = mnemonic.ToLegacyPrivateKey();
            Assert.Equal(key.LegacyDerive(-1).ToString(), MNEMONIC_LEGACY_PRIVATE_KEY);
        }

        virtual void ValidateGenerated24()
        {
            Mnemonic mnemonic = Mnemonic.Generate24();
            Mnemonic.FromString(mnemonic.ToString());
        }

        virtual void DeriveKeyIndex0()
        {
            Mnemonic iosMnemonic = Mnemonic.FromString(IOS_MNEMONIC_STRING);
            PrivateKey iosKey = PrivateKey.FromMnemonic(iosMnemonic);
            PrivateKey iosDerivedKey = iosKey.Derive(0);
            PrivateKey iosExpectedKey = PrivateKey.FromString(IOS_DEFAULT_PRIVATE_KEY);
            AssertThat(iosDerivedKey.ToBytes()).ContainsExactly(iosExpectedKey.ToBytes());
            Mnemonic androidMnemonic = Mnemonic.FromString(ANDROID_MNEMONIC_STRING);
            PrivateKey androidKey = PrivateKey.FromMnemonic(androidMnemonic);
            PrivateKey androidDerivedKey = androidKey.Derive(0);
            PrivateKey androidExpectedKey = PrivateKey.FromString(ANDROID_DEFAULT_PRIVATE_KEY);
            AssertThat(androidDerivedKey.ToBytes()).ContainsExactly(androidExpectedKey.ToBytes());
        }

        virtual void KeyFromGeneratedMnemonic24()
        {
            Mnemonic mnemonic = Mnemonic.Generate24();
            PrivateKey privateKey = PrivateKey.FromMnemonic(mnemonic);
            byte[] messageToSign = "this is a test message".GetBytes(StandardCharsets.UTF_8);
            byte[] signature = privateKey.Sign(messageToSign);
            Assertions.AssertThat(Ed25519.Verify(signature, 0, privateKey.GetPublicKey().ToBytes(), 0, messageToSign, 0, messageToSign.Length)).IsTrue();
        }

        virtual void KeyFromGeneratedMnemonic12()
        {
            Mnemonic mnemonic = Mnemonic.Generate12();
            PrivateKey privateKey = PrivateKey.FromMnemonic(mnemonic);
            byte[] messageToSign = "this is a test message".GetBytes(StandardCharsets.UTF_8);
            byte[] signature = privateKey.Sign(messageToSign);
            Assertions.AssertThat(Ed25519.Verify(signature, 0, privateKey.GetPublicKey().ToBytes(), 0, messageToSign, 0, messageToSign.Length)).IsTrue();
        }

        virtual void KeyFromEncryptedPem()
        {
            PrivateKey privateKey = PrivateKey.FromPem(ENCRYPTED_PEM, PEM_PASSPHRASE);
            Assert.Equal(privateKey.ToString(), TEST_KEY_STR);
        }

        virtual void ErrorKeyFromEncryptedPemNoPassphrase()
        {
            AssertThatExceptionOfType(typeof(BadKeyException)).IsThrownBy(() => PrivateKey.FromPem(ENCRYPTED_PEM)).Satisfies((error) => Assert.Equal(error.GetMessage(), "PEM file contained an encrypted private key but no passphrase was given"));
        }

        virtual void ReproducibleSignature(string keyStr)
        {
            PrivateKey key = PrivateKey.FromString(keyStr);
            byte[] signature = key.Sign(MESSAGE_BYTES);
            Assert.Equal(Hex.ToHexString(signature), SIG_STR);
        }

        virtual void KeyIsECDSA()
        {
            PrivateKey key = PrivateKey.GenerateED25519();
            AssertThat(key.IsED25519()).IsTrue();
        }

        virtual void KeyIsNotEd25519()
        {
            PrivateKey key = PrivateKey.GenerateED25519();
            AssertThat(key.IsECDSA()).IsFalse();
        }

        // TODO: replace with HexFormat.of().parseHex when the required Java version is 17
        public static byte[] HexStringToByteArray(string s)
        {
            int len = s.Length;
            byte[] data = new byte[len / 2];
            for (int i = 0; i < len; i += 2)
            {
                data[i / 2] = (byte)((Character.Digit(s.CharAt(i), 16) << 4) + Character.Digit(s.CharAt(i + 1), 16));
            }

            return data;
        }

        virtual void Slip10TestVector1()
        {

            // https://github.com/satoshilabs/slips/blob/master/slip-0010.md#test-vector-1-for-ed25519
            string CHAIN_CODE1 = "90046a93de5380a72b5e45010748567d5ea02bbf6522f979e05c0d8d8ca9fffb";
            string PRIVATE_KEY1 = "2b4be7f19ee27bbf30c667b642d5f4aa69fd169872f8fc3059c08ebae2eb19e7";
            string PUBLIC_KEY1 = "00a4b2856bfec510abab89753fac1ac0e1112364e7d250545963f135f2a33188ed";
            string CHAIN_CODE2 = "8b59aa11380b624e81507a27fedda59fea6d0b779a778918a2fd3590e16e9c69";
            string PRIVATE_KEY2 = "68e0fe46dfb67e368c75379acec591dad19df3cde26e63b93a8e704f1dade7a3";
            string PUBLIC_KEY2 = "008c8a13df77a28f3445213a0f432fde644acaa215fc72dcdf300d5efaa85d350c";
            string CHAIN_CODE3 = "a320425f77d1b5c2505a6b1b27382b37368ee640e3557c315416801243552f14";
            string PRIVATE_KEY3 = "b1d0bad404bf35da785a64ca1ac54b2617211d2777696fbffaf208f746ae84f2";
            string PUBLIC_KEY3 = "001932a5270f335bed617d5b935c80aedb1a35bd9fc1e31acafd5372c30f5c1187";
            string CHAIN_CODE4 = "2e69929e00b5ab250f49c3fb1c12f252de4fed2c1db88387094a0f8c4c9ccd6c";
            string PRIVATE_KEY4 = "92a5b23c0b8a99e37d07df3fb9966917f5d06e02ddbd909c7e184371463e9fc9";
            string PUBLIC_KEY4 = "00ae98736566d30ed0e9d2f4486a64bc95740d89c7db33f52121f8ea8f76ff0fc1";
            string CHAIN_CODE5 = "8f6d87f93d750e0efccda017d662a1b31a266e4a6f5993b15f5c1f07f74dd5cc";
            string PRIVATE_KEY5 = "30d1dc7e5fc04c31219ab25a27ae00b50f6fd66622f6e9c913253d6511d1e662";
            string PUBLIC_KEY5 = "008abae2d66361c879b900d204ad2cc4984fa2aa344dd7ddc46007329ac76c429c";
            string CHAIN_CODE6 = "68789923a0cac2cd5a29172a475fe9e0fb14cd6adb5ad98a3fa70333e7afa230";
            string PRIVATE_KEY6 = "8f94d394a8e8fd6b1bc2f3f49f5c47e385281d5c17e65324b0f62483e37e8793";
            string PUBLIC_KEY6 = "003c24da049451555d51a7014a37337aa4e12d41e485abccfa46b47dfb2af54b7a";
            var seed = HexStringToByteArray("000102030405060708090a0b0c0d0e0f");

            // Chain m
            PrivateKey key1 = PrivateKey.FromSeedED25519(seed);
            Assert.Equal(Hex.ToHexString(key1.GetChainCode().GetKey()), CHAIN_CODE1);
            Assert.Equal(key1.ToStringRaw(), PRIVATE_KEY1);
            AssertThat(key1.GetPublicKey().ToStringRaw()).IsSubstringOf(PUBLIC_KEY1);

            // Chain m/0'
            PrivateKey key2 = key1.Derive(0);
            Assert.Equal(Hex.ToHexString(key2.GetChainCode().GetKey()), CHAIN_CODE2);
            Assert.Equal(key2.ToStringRaw(), PRIVATE_KEY2);
            AssertThat(key2.GetPublicKey().ToStringRaw()).IsSubstringOf(PUBLIC_KEY2);

            // Chain m/0'/1'
            PrivateKey key3 = key2.Derive(1);
            Assert.Equal(Hex.ToHexString(key3.GetChainCode().GetKey()), CHAIN_CODE3);
            Assert.Equal(key3.ToStringRaw(), PRIVATE_KEY3);
            AssertThat(key3.GetPublicKey().ToStringRaw()).IsSubstringOf(PUBLIC_KEY3);

            // Chain m/0'/1'/2'
            PrivateKey key4 = key3.Derive(2);
            Assert.Equal(Hex.ToHexString(key4.GetChainCode().GetKey()), CHAIN_CODE4);
            Assert.Equal(key4.ToStringRaw(), PRIVATE_KEY4);
            AssertThat(key4.GetPublicKey().ToStringRaw()).IsSubstringOf(PUBLIC_KEY4);

            // Chain m/0'/1'/2'/2'
            PrivateKey key5 = key4.Derive(2);
            Assert.Equal(Hex.ToHexString(key5.GetChainCode().GetKey()), CHAIN_CODE5);
            Assert.Equal(key5.ToStringRaw(), PRIVATE_KEY5);
            AssertThat(key5.GetPublicKey().ToStringRaw()).IsSubstringOf(PUBLIC_KEY5);

            // Chain m/0'/1'/2'/2'/1000000000'
            PrivateKey key6 = key5.Derive(1000000000);
            Assert.Equal(Hex.ToHexString(key6.GetChainCode().GetKey()), CHAIN_CODE6);
            Assert.Equal(key6.ToStringRaw(), PRIVATE_KEY6);
            AssertThat(key6.GetPublicKey().ToStringRaw()).IsSubstringOf(PUBLIC_KEY6);
        }

        virtual void Slip10TestVector2()
        {

            // https://github.com/satoshilabs/slips/blob/master/slip-0010.md#test-vector-2-for-ed25519
            string CHAIN_CODE1 = "ef70a74db9c3a5af931b5fe73ed8e1a53464133654fd55e7a66f8570b8e33c3b";
            string PRIVATE_KEY1 = "171cb88b1b3c1db25add599712e36245d75bc65a1a5c9e18d76f9f2b1eab4012";
            string PUBLIC_KEY1 = "008fe9693f8fa62a4305a140b9764c5ee01e455963744fe18204b4fb948249308a";
            string CHAIN_CODE2 = "0b78a3226f915c082bf118f83618a618ab6dec793752624cbeb622acb562862d";
            string PRIVATE_KEY2 = "1559eb2bbec5790b0c65d8693e4d0875b1747f4970ae8b650486ed7470845635";
            string PUBLIC_KEY2 = "0086fab68dcb57aa196c77c5f264f215a112c22a912c10d123b0d03c3c28ef1037";
            string CHAIN_CODE3 = "138f0b2551bcafeca6ff2aa88ba8ed0ed8de070841f0c4ef0165df8181eaad7f";
            string PRIVATE_KEY3 = "ea4f5bfe8694d8bb74b7b59404632fd5968b774ed545e810de9c32a4fb4192f4";
            string PUBLIC_KEY3 = "005ba3b9ac6e90e83effcd25ac4e58a1365a9e35a3d3ae5eb07b9e4d90bcf7506d";
            string CHAIN_CODE4 = "73bd9fff1cfbde33a1b846c27085f711c0fe2d66fd32e139d3ebc28e5a4a6b90";
            string PRIVATE_KEY4 = "3757c7577170179c7868353ada796c839135b3d30554bbb74a4b1e4a5a58505c";
            string PUBLIC_KEY4 = "002e66aa57069c86cc18249aecf5cb5a9cebbfd6fadeab056254763874a9352b45";
            string CHAIN_CODE5 = "0902fe8a29f9140480a00ef244bd183e8a13288e4412d8389d140aac1794825a";
            string PRIVATE_KEY5 = "5837736c89570de861ebc173b1086da4f505d4adb387c6a1b1342d5e4ac9ec72";
            string PUBLIC_KEY5 = "00e33c0f7d81d843c572275f287498e8d408654fdf0d1e065b84e2e6f157aab09b";
            string CHAIN_CODE6 = "5d70af781f3a37b829f0d060924d5e960bdc02e85423494afc0b1a41bbe196d4";
            string PRIVATE_KEY6 = "551d333177df541ad876a60ea71f00447931c0a9da16f227c11ea080d7391b8d";
            string PUBLIC_KEY6 = "0047150c75db263559a70d5778bf36abbab30fb061ad69f69ece61a72b0cfa4fc0";
            var seed = HexStringToByteArray("fffcf9f6f3f0edeae7e4e1dedbd8d5d2cfccc9c6c3c0bdbab7b4b1aeaba8a5a29f9c999693908d8a8784817e7b7875726f6c696663605d5a5754514e4b484542");

            // Chain m
            PrivateKey key1 = PrivateKey.FromSeedED25519(seed);
            Assert.Equal(Hex.ToHexString(key1.GetChainCode().GetKey()), CHAIN_CODE1);
            Assert.Equal(key1.ToStringRaw(), PRIVATE_KEY1);
            AssertThat(key1.GetPublicKey().ToStringRaw()).IsSubstringOf(PUBLIC_KEY1);

            // Chain m/0'
            PrivateKey key2 = key1.Derive(0);
            Assert.Equal(Hex.ToHexString(key2.GetChainCode().GetKey()), CHAIN_CODE2);
            Assert.Equal(key2.ToStringRaw(), PRIVATE_KEY2);
            AssertThat(key2.GetPublicKey().ToStringRaw()).IsSubstringOf(PUBLIC_KEY2);

            // Chain m/0'/2147483647'
            PrivateKey key3 = key2.Derive(2147483647);
            Assert.Equal(Hex.ToHexString(key3.GetChainCode().GetKey()), CHAIN_CODE3);
            Assert.Equal(key3.ToStringRaw(), PRIVATE_KEY3);
            AssertThat(key3.GetPublicKey().ToStringRaw()).IsSubstringOf(PUBLIC_KEY3);

            // Chain m/0'/2147483647'/1'
            PrivateKey key4 = key3.Derive(1);
            Assert.Equal(Hex.ToHexString(key4.GetChainCode().GetKey()), CHAIN_CODE4);
            Assert.Equal(key4.ToStringRaw(), PRIVATE_KEY4);
            AssertThat(key4.GetPublicKey().ToStringRaw()).IsSubstringOf(PUBLIC_KEY4);

            // Chain m/0'/2147483647'/1'/2147483646'
            PrivateKey key5 = key4.Derive(2147483646);
            Assert.Equal(Hex.ToHexString(key5.GetChainCode().GetKey()), CHAIN_CODE5);
            Assert.Equal(key5.ToStringRaw(), PRIVATE_KEY5);
            AssertThat(key5.GetPublicKey().ToStringRaw()).IsSubstringOf(PUBLIC_KEY5);

            // Chain m/0'/2147483647'/1'/2147483646'/2'
            PrivateKey key6 = key5.Derive(2);
            Assert.Equal(Hex.ToHexString(key6.GetChainCode().GetKey()), CHAIN_CODE6);
            Assert.Equal(key6.ToStringRaw(), PRIVATE_KEY6);
            AssertThat(key6.GetPublicKey().ToStringRaw()).IsSubstringOf(PUBLIC_KEY6);
        }

        virtual void PEMImportTestVectors()
        {

            // https://github.com/hashgraph/hedera-sdk-reference/issues/93#issue-1665972122
            var PRIVATE_KEY_PEM1 = "-----BEGIN PRIVATE KEY-----\n" + "MC4CAQAwBQYDK2VwBCIEIOgbjaHgEqF7PY0t2dUf2VU0u1MRoKii/fywDlze4lvl\n" + "-----END PRIVATE KEY-----";
            var PRIVATE_KEY1 = "e81b8da1e012a17b3d8d2dd9d51fd95534bb5311a0a8a2fdfcb00e5cdee25be5";
            var PUBLIC_KEY1 = "f7b9aa4a8e4eee94e4277dfe757d8d7cde027e7cd5349b7d8e6ee21c9b9395be";
            var PRIVATE_KEY_PEM2 = "-----BEGIN ENCRYPTED PRIVATE KEY-----\n" + "MIGbMFcGCSqGSIb3DQEFDTBKMCkGCSqGSIb3DQEFDDAcBAiho4GvPxvL6wICCAAw\n" + "DAYIKoZIhvcNAgkFADAdBglghkgBZQMEAQIEEIdsubXR0QvxXGSprqDuDXwEQJZl\n" + "OBtwm2p2P7WrWE0OnjGxUe24fWwdrvJUuguFtH3FVWc8C5Jbxgbyxsuzbf+utNL6\n" + "0ey+WdbGL06Bw0HGqs8=\n" + "-----END ENCRYPTED PRIVATE KEY-----";
            var PRIVATE_KEY2 = "fa0857e963946d5f5e035684c40354d3cd3dcc80c0fb77beac2ef7c4b5271599";
            var PUBLIC_KEY2 = "202af61e141465d4bf2c356d37d18bd026c246bde4eb73258722ad11f790be4e";
            var ed25519PrivateKey1 = PrivateKey.FromPem(PRIVATE_KEY_PEM1);
            Assert.Equal(ed25519PrivateKey1.ToStringRaw(), PRIVATE_KEY1);
            Assert.Equal(ed25519PrivateKey1.GetPublicKey().ToStringRaw(), PUBLIC_KEY1);
            var ed25519PrivateKey2 = PrivateKey.FromPem(PRIVATE_KEY_PEM2, TEST_VECTOR_PEM_PASSPHRASE);
            Assert.Equal(ed25519PrivateKey2.ToStringRaw(), PRIVATE_KEY2);
            Assert.Equal(ed25519PrivateKey2.GetPublicKey().ToStringRaw(), PUBLIC_KEY2);
        }

        virtual void DERImportTestVectors()
        {

            // https://github.com/hashgraph/hedera-sdk-reference/issues/93#issue-1665972122
            var PRIVATE_KEY_DER1 = "302e020100300506032b657004220420feb858a4a69600a5eef2d9c76f7fb84fc0b6627f29e0ab17e160f640c267d404";
            var PRIVATE_KEY1 = "feb858a4a69600a5eef2d9c76f7fb84fc0b6627f29e0ab17e160f640c267d404";
            var PUBLIC_KEY1 = "8ccd31b53d1835b467aac795dab19b274dd3b37e3daf12fcec6bc02bac87b53d";
            var ed25519PrivateKey1 = PrivateKey.FromStringDER(PRIVATE_KEY_DER1);
            Assert.Equal(ed25519PrivateKey1.ToStringRaw(), PRIVATE_KEY1);
            Assert.Equal(ed25519PrivateKey1.GetPublicKey().ToStringRaw(), PUBLIC_KEY1);
        }
    }
}